### ISSUE TITLE
Launch at startup action is not ideal (and doesn’t work properly)

### ISSUE THREAD

**Issue by vitorgalvao** [jefbarn/Sonarr-Menu#1]
To make Sonarr-Menu start at login, it should be [added as a login item](https://hamstergene.github.io/post/editing-osx-login-items-cmdline/), not setup as a launch daemon under the user’s `LaunchAgents` dir.

Furthermore, even that solution doesn’t work if `~/Library/LaunchAgents` doesn’t already exist (which it doesn’t, by default), so adding it needs to create the directory if it doesn’t already exist.

**Comment by jefbarn** [comment]
Apple has deprecated Login Items as of 10.11.  To quote LSSharedFileList.h, "Use a LaunchAgent, XPCService or the ServiceManagement APIs instead."
I'll add a check to make sure the directory is created, thanks for catching that.
